### ISSUE TITLE
fatih/color is archived

### ISSUE THREAD

**Issue by is2ei** [mingrammer/cfmt#4]
https://github.com/fatih/color is archived. It might be needed to look for another lib.

**Comment by mingrammer** [comment]
Hi is2ei! Thanks for informing that news. I didn't know that.

`cfmt` is currently using `fatih/color` as core library for coloring. The current version of `color` is stable and `cfmt` has no any problems with it. So, at least for now, there is no reason to use another library.

Of course, if `cfmt` has a problem with unmaintained `color` library later, I'll consider using another library.

**Comment by mingrammer** [comment]
I'll leave this issue for later on.

**Comment by is2ei** [comment]
@mingrammer  Do you mind if I send you PR?

**Comment by mingrammer** [comment]
@is2ei Sure! PR is always welcome. You just have to pass the tests :)
